# ===============================
# CONEXIÓN A MYSQL
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/taberna_yarel_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
# IMPORTANTE: Reemplaza esto con la contraseña que usas para entrar a MySQL Workbench:
spring.datasource.password=tu_contraseña_aqui
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ===============================
# Como ya creamos las tablas con el script SQL, le decimos a Spring que NO intente crearlas de nuevo
spring.jpa.hibernate.ddl-auto=none

# Estas líneas nos permitirán ver en la consola las consultas SQL que Spring hace por debajo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
